#FROM node:16.13.1-alpine
FROM node:12-alpine3.11
#WORKDIR /usr/src/app
#FROM node:latest
WORKDIR /usr/src/app
#RUN npm install -g

#RUN chown -Rh  /usr/src/app

#EXPOSE 3000

#CMD [ "sh", "-c", "npm install && npm run start" ]
#WORKDIR /usr/src/app
COPY package*.json ./
#ENV HOST 0.0.0.0
#RUN npm install
#COPY . .
#EXPOSE 3000
#CMD [ "npm", "start" ]
#CMD [ "sh", "-c", "npm install && npm run dev" ]
